### ISSUE TITLE
after connecting with firebase app is not working

### ISSUE THREAD

**Issue by HumayraAfrin** [aws1994/BlogApp#2]
Process: com.example.bookfinderapp, PID: 30550
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at com.example.bookfinderapp.Activities.RegisterActivity.CreateUserAccount(RegisterActivity.java:119)
        at com.example.bookfinderapp.Activities.RegisterActivity.access$600(RegisterActivity.java:36)
        at com.example.bookfinderapp.Activities.RegisterActivity$1.onClick(RegisterActivity.java:90)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22651)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6267)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by aws1994** [comment]
please recheck your progress bar

**Comment by ddyachok** [comment]
I have the same problem, even on your app, downloaded from github😭

**Comment by AlephQuiroz** [comment]
they found the solution?' 😭😭😭
